# TCL File Generated by Component Editor 12.1sp1
# Sat Mar 09 23:00:45 JST 2013
# DO NOT MODIFY


# 
# usbhost_component "usbhost_component" v1.0
# null 2013.03.09.23:00:45
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module usbhost_component
# 
set_module_property NAME usbhost_component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Peripherals
set_module_property DISPLAY_NAME usbhost_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL usbhost_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file usbhost_component.v VERILOG PATH usbhost_component.v


# 
# parameters
# 
add_parameter HOST_FIFO_DEPTH INTEGER 64
set_parameter_property HOST_FIFO_DEPTH DEFAULT_VALUE 64
set_parameter_property HOST_FIFO_DEPTH DISPLAY_NAME HOST_FIFO_DEPTH
set_parameter_property HOST_FIFO_DEPTH TYPE INTEGER
set_parameter_property HOST_FIFO_DEPTH ENABLED false
set_parameter_property HOST_FIFO_DEPTH UNITS None
set_parameter_property HOST_FIFO_DEPTH HDL_PARAMETER true
add_parameter HOST_FIFO_ADDR_WIDTH INTEGER 6
set_parameter_property HOST_FIFO_ADDR_WIDTH DEFAULT_VALUE 6
set_parameter_property HOST_FIFO_ADDR_WIDTH DISPLAY_NAME HOST_FIFO_ADDR_WIDTH
set_parameter_property HOST_FIFO_ADDR_WIDTH TYPE INTEGER
set_parameter_property HOST_FIFO_ADDR_WIDTH ENABLED false
set_parameter_property HOST_FIFO_ADDR_WIDTH UNITS None
set_parameter_property HOST_FIFO_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits SYMBOLS
set_interface_property s1 associatedClock clock_s1
set_interface_property s1 associatedReset reset_s1
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_address address Input 8
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_readdata readdata Output 8
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 8
add_interface_port s1 avs_s1_waitrequest waitrequest Output 1
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point irq_s1
# 
add_interface irq_s1 interrupt end
set_interface_property irq_s1 associatedAddressablePoint s1
set_interface_property irq_s1 associatedClock clock_s1
set_interface_property irq_s1 associatedReset reset_s1
set_interface_property irq_s1 ENABLED true

add_interface_port irq_s1 avs_s1_irq irq Output 1


# 
# connection point usbport
# 
add_interface usbport conduit end
set_interface_property usbport associatedClock ""
set_interface_property usbport associatedReset ""
set_interface_property usbport ENABLED true

add_interface_port usbport test_dataouttick export Output 1
add_interface_port usbport test_dataintick export Output 1
add_interface_port usbport usbclk_48mhz export Input 1
add_interface_port usbport usb_dp export Bidir 1
add_interface_port usbport usb_dm export Bidir 1
add_interface_port usbport usb_oe_n export Output 1
add_interface_port usbport usb_fullspeed export Output 1


# 
# connection point clock_s1
# 
add_interface clock_s1 clock end
set_interface_property clock_s1 clockRate 0
set_interface_property clock_s1 ENABLED true

add_interface_port clock_s1 avs_s1_clk clk Input 1


# 
# connection point reset_s1
# 
add_interface reset_s1 reset end
set_interface_property reset_s1 associatedClock clock_s1
set_interface_property reset_s1 synchronousEdges DEASSERT
set_interface_property reset_s1 ENABLED true

add_interface_port reset_s1 avs_s1_reset reset Input 1

